<a href="https://www.kaggle.com/code/vladyslavtkachuk/pytorch?scriptVersionId=295129560" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>


Ваша задача методом градієнтного спуску побудувати модель для прогнозу ціни на діаманти

In [7]:
import pandas as pd

In [15]:
df = pd.read_csv("/kaggle/input/diamonds/diamonds.csv", index_col=0)
df.head()

,carat,price
0,0.23,326
1,0.21,326
2,0.23,327
3,0.29,334
4,0.31,335


Формула моделі
$$
          pred = coef*carat + intercept
$$
* coef - ціна за один карат
* intercept - витрати
  
  
<br>
<br>
Формула для ображунку похибки

$$
          loss = mean((pred - price)^2)
$$

* pred - ціна, спрогнозована моделю
* price - справжня ціна

In [18]:
# імпорт модуля
import torch


carat = df['carat'].to_numpy()
price = df['price'].to_numpy()

# вага в каратах
carat = torch.tensor(carat, dtype=torch.float32)

# справжня ціна
price = torch.tensor(price, dtype=torch.float32)

In [19]:
# створіть тензори з градієнтом, оберіть довільне початкове значення, тип даних float32
coef = torch.tensor(1.0, requires_grad=True)
intercept = torch.tensor(5.0, requires_grad=True)

# вкажіть навчальний крок
learning_rate = 0.01

# визначення оптимізатора
from torch.optim import SGD
optimizer = SGD([coef, intercept], lr=learning_rate)

# основний цикл
for t in range(2000):
  # обрахуйте прогноз моделі за формулою наведеною вище
    pred = coef * carat + intercept
    
  # обрахуйте похибку між справжньою ціною та прогнозованою
    error = (pred - price)**2
    loss = error.mean()
    
  # виведіть значення похибки для кожного сотого кроку
    if t % 100 == 0:
        print(error)

  # обрахуйте градієнти по метриці
  # градієнтний спуск
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()


print(f"Optimized coef: {coef}, optimized intercept: {intercept}")

tensor([ 102893.3828,  102906.2266,  103535.9297,  ..., 7569652.0000,
        7568770.5000, 7569376.5000], grad_fn=<PowBackward0>)
tensor([3748899.5000, 3477699.5000, 3745028.2500,  ..., 1396878.1250,
        3071899.7500, 1850326.5000], grad_fn=<PowBackward0>)
tensor([1904893.2500, 1660499.0000, 1902133.8750,  ..., 1212631.1250,
        3362812.7500, 1769254.6250], grad_fn=<PowBackward0>)
tensor([ 780966.6250,  604621.5000,  779200.1250,  ...,  897228.9375,
        3227100.0000, 1470384.2500], grad_fn=<PowBackward0>)
tensor([ 248876.9375,  145555.9844,  247880.1875,  ...,  681911.0625,
        3113953.0000, 1252548.3750], grad_fn=<PowBackward0>)
tensor([  40817.0703,    5780.8252,   40414.0039,  ...,  535889.0625,
        3027770.0000, 1096305.1250], grad_fn=<PowBackward0>)
tensor([7.2289e+02, 2.5457e+04, 7.7766e+02,  ..., 4.3528e+05, 2.9621e+06,
        9.8292e+05], grad_fn=<PowBackward0>)
tensor([  41381.3047,  116437.8125,   41789.1523,  ...,  364829.2812,
        2911995.5000,  89

# Результат

In [ ]:
coef.item(), intercept.item()

# Порівняйте результат з sklearn

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
X_train = df.drop(columns=['price'])
y_train = df['price']
# тренування
model.fit(X_train, y_train)

In [ ]:
model.coef_[0], model.intercept_